apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-web-svc

spec:
  selector:
    app: {{ include "chart.fullname" . }}-web

  ports:
    - name: web-port
      port: {{ .Values.service.web.port }}
      targetPort: {{ .Values.service.web.targetPort }}
      protocol: {{ .Values.service.web.protocol }}

  type: {{ .Values.service.web.type }}