replicaCount: 1
image:
  repository: mahin96/django-traefik
  pullPolicy: Always
  tag: c2f4d3387d02c8506c176093b20a973b62d413ff
containerPort: 8000
restartPolicy: Always

service:
  web:
    type: NodePort
    port: 8000
    protocol: TCP
    targetPort: 8000
